### ISSUE TITLE
CMS and C-grids

### ISSUE THREAD

**Issue by sambarluc** [beatrixparis/connectivity-modeling-system#10]
Hi, I am planning some particle tracking simulations of Lake Geneva. I am using MITgcm to do the simulations, and I have my hydrodynamic fields on an orthogonal curvilinear C-grid. I am thus forced to do some non trivial interpolation to go to the A-grid that CMS requires. Non trivial in particular because I would like to keep my flow non divergent.

I read in the manual that there is work underway to have CMS working with a broader class of grids. Has there been any progress on this side? I am considering to work on this issue myself but, before diving into the code, I was hoping to have some feedback from people who already know CMS well.

Thanks, Adnrea

**Comment by beatrixparis** [comment]
Hello Andrea,


Thank you for the note. We are still working on this problem. However let me remind you that CMS is an open-source community modeling system, which means that we expect feedback from users with new code - in that way code exchange will go two ways between the developers (Paris Lab)  and the users. Therefore, I strongly suggest to continue working on the interpolation scheme for MITgcm and submit it on GitHub whenever ready as a patch. It will be a great module that I will be happy to include it in the CMS package.


https://github.com/beatrixparis/connectivity-modeling-system


Many thanks!


Claire


Claire B. Paris-Limouzy, PhD
Associate Professor
____________________________________

Department of Ocean Sciences
Rosenstiel School of Marine & Atmospheric Science
University of Miami
4600 Rickenbacker Causeway, Miami, FL 33149-1098, USA
Phone: 305-421-4219, Fax: 305-421-4701
Marine Technology & Life Science Seawater (MTLSS) #245

Physical-Biological Interactions Lab | http://www.rsmas.miami.edu/personal/cparis
Facebook: http://www.facebook.com/parislab
Research Gate: https://www.researchgate.net/profile/Claire_Paris

Topic Editor of ICES Journal of Marine Science
Freediving US National Record Holder DNF

“If you lose small things everything else fails” Louie Psihoyos


________________________________

**Comment by anacarolvaz** [comment]
Hello Andrea,

I also want to let you know that we have an user group for CMS, where you can post your questions:
