### ISSUE TITLE
Editing src/mpi_compiler for branch: TempMort_Module

### ISSUE THREAD

**Issue by salwood82** [beatrixparis/connectivity-modeling-system#24]
This branch has been created to incorporate the effect of temperature on larval survival. It needs testing by other users before it can be merged with the master branch for general use. However, I am not sure how to incorporate the new module (mod_TempMort.f90) into src/mpi_compiler?

**Comment by anacarolvaz** [comment]
Hi Sally! I hope all is well with you - I've just seen your message now, have you found a solution to this?

You need to incorporate it on the Makefile - just find where is the list of mod_ and added it - 

eg.

MODS =  mod_kinds.o def_constants.o (etc etc) mod_TempMort.o

Then at the end there is a list of object files and which fortran file corresponds to them:
mod_random.o: mod_random.f90
mod_netcdfoutput.o: mod_netcdfoutput.f90
mod_directory.o: mod_directory.c mod_directory.h
mod_ibio: mod_ibio.f90
mod_strata.o: mod_strata.f90
mod_turb.o: mod_turb.f90

You need to include your mod there - after whatever other modules it uses to run, before the ones that call it 
mod_TempMort.o: mod_TempMort.f90

I hope this have helped, send me a message if not.
