### ISSUE TITLE
IEEE_DIVIDE_BY_ZERO

### ISSUE THREAD

**Issue by shilpafiji** [beatrixparis/connectivity-modeling-system#26]
hi, 

I am trying to do a simulation of fish larvae using the vertical migration option. My release depth is 1m. and my vertical matrix is as follows:

3
2
10 50 
1728000 1728000 2073600
100 0 100
0 100 0

when execute the cms run, I get an error saying "  Depth in release file is greater than depths in vert_matrix file
Note: The following floating-point exceptions are signalling: IEEE_DIVIDE_BY_ZERO"

But, the depths in my release file are not greater than the depths in the vert_matrix file. Why do I get this error? What should I do?

Here's what I got:
~/cms/connectivity-modeling-system-master/cms-master/expt $ ./cms 280915
 ibiotimestep         300
 ==========================================
 File name  : traj_file_1.nc
 Total number release locations     : 54 (1 to 54)
 Total number of particles released : 5400
 Total number of time steps   : 18757
 Total number of time steps in output file: 1561
 Depth in release file is greater than depths in vert_matrix file
Note: The following floating-point exceptions are signalling: IEEE_DIVIDE_BY_ZERO

Thanks 
shilpafiji

**Comment by beatrixparis** [comment]
Hello Shilpafiji

Your vertical matrix file looks ok. Can you please send me your release file?

Thanks!

 Claire Beatrix Paris
 —Sent from iPhone

________________________________________

**Comment by shilpafiji** [comment]
[releaseFile0928151m.txt](https://github.com/beatrixparis/connectivity-modeling-system/files/1778082/releaseFile0928151m.txt)

Thanks
Shilpa

**Comment by shilpafiji** [comment]
The issue is solved by having greater depths in the vertical matrix file. 
Here's the new vertical matrix file that I made and it works!

3
3
10 50 200
1728000 1728000 2073600
100 0 100
0 100 0
0 0 0 

Thanks 
Shilpa
