### ISSUE TITLE
About compilers

### ISSUE THREAD

**Issue by lalvaresanramaria** [beatrixparis/connectivity-modeling-system#28]
Hello 

I'm new at the CMS and I'm trying to install it but got a error while compilling, this is it

lalvarez@lalvarez-H61MLV ~/CMS/src $ make
mpif90 -c mod_kinds.f90 -I/usr/local/netcdf/include -I/usr/local/include 
make: mpif90: No se encontró el programa
make: *** [mod_kinds.o] Error 127

I have a i7 intel processor and have gfortran compiler, do I need to change

# Makefile
#the Fortran compiler to create object files
FC            = mpif90

for 

FC            = gfortran

Can any one give me a hand
Thanks in advance

**Comment by anacarolvaz** [comment]
Hi, I have only seen your message now. Have you updated your compiler on your arch directory? After updating it, you need to include it on your Makefile, i.e. 

include ../arch/the_name_of_your_compiler

If you are not using MPI, you also need to comment some lines on cms.f90. We are updating the code so we don't need to do this, but for now you will need to (all lines saying to comment if not using MPI).

You should also join the user group to get feedback from the community of users:
https://groups.google.com/forum/#!forum/connectivity-modeling-system-club

Cheers,
Ana
