### ISSUE TITLE
exit code = -2 

### ISSUE THREAD

**Issue by shilpafiji** [beatrixparis/connectivity-modeling-system#32]
Hi 

I am getting exit code of -2 even though avoid coast is set to true. 
What could be causing this?
I am using two nest files. Could the particles have gone between the two nest files and stopped moving? 
Does CMS remove particles that have stopped moving with an exit code of -2 even though avoid coast is set to true? 

Thanks 
Shilpa

**Comment by bexeross** [comment]
Hi Shilpa,

The -2 exit code can also be a sign that you are releasing particles from a point that the model considers to be already "on land". These are easily identified as usually giving the -2 exit code after only one time step. Particles that are free to move at point of release are the ones that will be affected by the avoidcoast funciton. 

For example: if your nest files are 1 day/86400 seconds apart and you set the model to have a 1 hour timestep/3600 seconds, you'll see that even with only two nest files, any points released from land are easily detected as having a -2 exit code after only 3600seconds, while other particles report their exit code after a maximum run length, such as 86400 seconds.

As I don't think you are reporting an error in the model, and we are reserving this github area for suggestions for model changes, can I recommend you [join our forum](https://groups.google.com/forum/#!forum/connectivity-modeling-system-club) and post any additional issues there. We'd be happy to help you further there if you are still having issues, and there are many existing questions and answers there which maybe helpful to you going forward.

All the best,
Bex

**Comment by shilpafiji** [comment]
Hi Bex, 

Thank you so much for the reply. I will definitely join the forum and post issues there. 
 
Thanks  
Shilpa
