### ISSUE TITLE
Compiling error and Google forums

### ISSUE THREAD

**Issue by anthonysnead** [beatrixparis/connectivity-modeling-system#35]
When running make I get numerous errors that all look like this: f951: Warning: Nonexistent include directory ‘/usr/local/netcdf/include’ [-Wmissing-include-dirs}]. I have mpif90, gfortran, and gcc installed. I have the netcdf libraries installed but once I looked it up it is installed in the -I/usr/include path. I cannot figure out how to change the the -I paths in the mpif90 settings. 

On another note, I have been trying the find the google forum, but It says either this forum does not exist or I need permission to see it. The answer may be in the forum, but I do not have access. I appreciate your time.
Respectfully,
Anthony Snead

**Comment by anacarolvaz** [comment]
Hi Anthony,

Beck sent you the link on the other entry, but here is the user group, you should be able to access it:
https://groups.google.com/forum/#!forum/connectivity-modeling-system-club

For the other error, you need to include the path to the correct directories of your libraries on your mpi_compiler file, located on the arch directory. This information is also on the user guide if you need more details

If you can't join the group, send your email and we can send you an invitation.
Ana
