### ISSUE TITLE
missing input polygon in input_example

### ISSUE THREAD

**Issue by zdefne-usgs** [beatrixparis/connectivity-modeling-system#5]
Error: File input_example/poly10km.xyz Does not exist

**Comment by beatrixparis** [comment]
Dear Zafer

It seems that you have not been creating the correct directories and input files on your computer or the server you are using to run the CMS. We are providing an example in the user's guide. Please read it carefully. 

Thanks 

Prof Claire Paris

**Comment by anacarolvaz** [comment]
Included example file.
